// stage.js — the 3D picture of a studio scene on top of ArcEngine:
// World3D/View3D (light, sky, fog, toon shader, ink edges, outlines, shadows), Terrain3D
// (flat ground), Gltf3D (skinned characters with clips). The studio adds a procedural city,
// scene props, actors driven by the baked frames (StudioSim) and the scene camera.
// The stage never decides motion: it only shows the frame for time t.
// LICENCE RULE (decision of 09.10.2026): no files from ArcEngine assets/ (no licence) — the city,
// props, textures and characters are generated by code; third-party assets only under CC0.
// One engine: Babylon.js (Apache-2.0) inside ArcEngine; no three.js, no Theatre.js.

/** @satisfies {Record<string, any>} */
const StudioCity = {
    P: 2600,       // street pitch, px (1 px = 1 cm)
    ROAD: 800,     // road width
    WALK: 260,     // sidewalk band inside each block edge

    // Seeded random: the same seed -> the same city on every device.
    rng(seed) {
        let s = (seed * 2654435761) >>> 0 || 1;
        return () => { s ^= s << 13; s >>>= 0; s ^= s >> 17; s ^= s << 5; s >>>= 0; return s / 4294967296; };
    },

    color(hex) { return World3D.hexColor3(hex); },

    mat(scene, name, hex, opts) {
        const m = new BABYLON.StandardMaterial(name, scene);
        m.diffuseColor = this.color(hex);
        if (opts && opts.emissive) m.emissiveColor = this.color(opts.emissive);
        if (opts && opts.texture) m.diffuseTexture = opts.texture;
        World3D.applyMaterialConstants(m);
        return m;
    },

    // Facade texture: wall + a 2×2 window grid per tile. Drawn on a canvas: no image files,
    // works from file:// too.
    facadeTexture(scene) {
        const c = document.createElement('canvas');
        c.width = c.height = 128;
        const g = c.getContext('2d');
        g.fillStyle = '#ffffff';
        g.fillRect(0, 0, 128, 128);
        for (let i = 0; i < 2; i++) for (let j = 0; j < 2; j++) {
            const x = 14 + i * 64, y = 16 + j * 64;
            g.fillStyle = '#6f9fb0';
            g.fillRect(x, y, 36, 34);
            g.fillStyle = '#a9dbe6';
            g.fillRect(x + 3, y + 3, 14, 28);
            g.fillStyle = '#e8f7fa';
            g.fillRect(x + 20, y + 3, 4, 28);
            g.fillStyle = '#d7dee2';
            g.fillRect(x - 3, y + 34, 42, 5);
        }
        const tex = new BABYLON.DynamicTexture('facade', c, scene, true, BABYLON.Texture.TRILINEAR_SAMPLINGMODE);
        tex.update(false);
        tex.wrapU = tex.wrapV = BABYLON.Texture.WRAP_ADDRESSMODE;
        tex.anisotropicFilteringLevel = 4;
        return tex;
    },

    // Build the city into the view. -> { meshes }
    build(view, world) {
        const scene = view.scene, P = this.P, R = this.ROAD, W = this.WALK;
        const rnd = this.rng((world && world.seed) || 7);
        const plaza = (world && world.plaza) || [-9, -9];
        const facade = this.facadeTexture(scene);
        const palette = ['#f3f6f4', '#cfeff0', '#ecdcc6', '#d7e1ea', '#bfe6e0'];
        const groups = new Map();   // material key -> meshes to merge
        const add = (key, mesh) => { if (!groups.has(key)) groups.set(key, []); groups.get(key).push(mesh); };
        const box = (w, h, d, x, y, z, uvTile) => {
            const opts = { width: w, height: h, depth: d };
            if (uvTile) {
                const u = Math.max(1, Math.round(w / uvTile)), uz = Math.max(1, Math.round(d / uvTile)), v = Math.max(1, Math.round(h / uvTile));
                const roof = new BABYLON.Vector4(0, 0, 0.05, 0.05);
                // faces: 0 back(+z?) 1 front 2 right 3 left 4 top 5 bottom (Babylon box order)
                opts.faceUV = [new BABYLON.Vector4(0, 0, u / 2, v / 2), new BABYLON.Vector4(0, 0, u / 2, v / 2),
                    new BABYLON.Vector4(0, 0, uz / 2, v / 2), new BABYLON.Vector4(0, 0, uz / 2, v / 2), roof, roof];
            }
            const m = BABYLON.MeshBuilder.CreateBox('b', opts, scene);
            m.position.set(x, y + h / 2, z);
            return m;
        };

        for (let bi = -1; bi <= 4; bi++) for (let bj = -1; bj <= 4; bj++) {
            const x0 = bi * P + R / 2, y0 = bj * P + R / 2, size = P - R;
            const isPlaza = bi === plaza[0] && bj === plaza[1];
            // Sidewalk slab (the whole block), curb height 14 px
            add(isPlaza ? 'plazaFloor' : 'walk', box(size, 14, size, x0 + size / 2, 0, y0 + size / 2));
            if (isPlaza) { this._plaza(add, box, scene, x0, y0, size, rnd); continue; }
            // 2×2 lots, some merged into one big building
            const lots = rnd() < 0.3 ? [[0, 0, 2, 2]] : [[0, 0, 1, 1], [1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 1, 1]];
            const half = (size - 2 * W) / 2;
            for (const [li, lj, sw, sh] of lots) {
                const gap = 40;
                const w = half * sw - gap - rnd() * 120, d = half * sh - gap - rnd() * 120;
                const h = 700 + Math.floor(rnd() * 6) * 380 + (sw > 1 ? 900 : 0);
                const cx = x0 + W + half * li + half * sw / 2, cy = y0 + W + half * lj + half * sh / 2;
                const col = Math.floor(rnd() * palette.length);
                add('bld' + col, box(w, h, d, cx, 14, cy, 300));
                // Roof parapet and a roof unit
                add('roof', box(w + 24, 40, d + 24, cx, 14 + h, cy));
                if (rnd() < 0.8) add('roofUnit', box(160 + rnd() * 160, 90 + rnd() * 80, 140 + rnd() * 140, cx + (rnd() - 0.5) * w * 0.5, 54 + h, cy + (rnd() - 0.5) * d * 0.5));
                // Shop awning on the ground floor facing a street
                if (rnd() < 0.5) add('awning', box(Math.min(w * 0.7, 520), 26, 90, cx, 300, cy + d / 2 + 45));
            }
            // Street trees on the sidewalk, lamps at the corners
            for (let k = 0; k < 3; k++) {
                const tx = x0 + 300 + k * (size - 600) / 2, ty = y0 + 130;
                if (rnd() < 0.7) this._tree(add, scene, tx, ty, 0.8 + rnd() * 0.4);
            }
            this._lamp(add, scene, x0 + 70, y0 + 70);
            this._lamp(add, scene, x0 + size - 70, y0 + size - 70);
        }
        // Road markings: dashed center lines and zebra crossings at every intersection
        for (let k = 0; k <= 4; k++) {
            for (let s = -P + 600; s < 5 * P; s += 420) {
                if (((s % P) + P) % P > P - 700 || ((s % P) + P) % P < 700) continue;   // not across a junction
                add('paint', box(200, 2, 14, s, 0, k * P));
                add('paint', box(14, 2, 200, k * P, 0, s));
            }
            for (let m = 0; m <= 4; m++) {
                const cx = k * P, cy = m * P;
                for (let z = -5; z <= 5; z++) {
                    add('paint', box(60, 2, 220, cx + z * 70, 0, cy - R / 2 - 160));
                    add('paint', box(220, 2, 60, cx - R / 2 - 160, 0, cy + z * 70));
                }
            }
        }
        // Parked cars along the curbs
        const carCols = ['#2bdff9', '#ff6b4a', '#f4f7f6', '#1f3550', '#e8b100'];
        for (let n = 0; n < 26; n++) {
            const vertical = rnd() < 0.5, k = 1 + Math.floor(rnd() * 3), along = rnd() * 4 * P + 400;
            if (((along % P) + P) % P < 900 || ((along % P) + P) % P > P - 900) continue;
            const side = rnd() < 0.5 ? -1 : 1, off = side * (R / 2 - 70);
            const x = vertical ? k * P + off : along, y = vertical ? along : k * P + off;
            this._car(add, scene, x, y, vertical, carCols[n % carCols.length]);
        }

        const mats = {
            walk: this.mat(scene, 'walk', '#d9e3e2'), plazaFloor: this.mat(scene, 'plaza', '#e9efe6'),
            roof: this.mat(scene, 'roof', '#9fb4bc'), roofUnit: this.mat(scene, 'roofUnit', '#c8d3d7'),
            awning: this.mat(scene, 'awning', '#2bc4dd'), paint: this.mat(scene, 'paint', '#f7fbfc'),
            trunk: this.mat(scene, 'trunk', '#7a5a43'), leaf: this.mat(scene, 'leaf', '#58c29a'),
            lamp: this.mat(scene, 'lamp', '#3b4b55'), lampHead: this.mat(scene, 'lampHead', '#bff6ff', { emissive: '#2a8fa0' }),
            grass: this.mat(scene, 'grass', '#86d39f'), water: this.mat(scene, 'water', '#59d8ee', { emissive: '#167f92' }),
            stone: this.mat(scene, 'stone', '#cfd8d6'), glass: this.mat(scene, 'glass', '#1d3b4a'),
            tyre: this.mat(scene, 'tyre', '#1b2228')
        };
        palette.forEach((hex, i) => { mats['bld' + i] = this.mat(scene, 'bld' + i, hex, { texture: facade }); });
        for (const hex of carCols) mats['car' + hex] = this.mat(scene, 'car' + hex, hex);

        const meshes = [];
        for (const [key, list] of groups) {
            const merged = BABYLON.Mesh.MergeMeshes(list, true, true);
            if (!merged) continue;
            merged.name = 'city/' + key;
            merged.material = mats[key];
            merged.freezeWorldMatrix();
            merged.isPickable = false;
            // Paint and floors lie flat: no shadow casting, no ink edges, no outline
            const flat = key === 'paint' || key === 'walk' || key === 'plazaFloor' || key === 'grass';
            World3D.addObject(view, merged, 'prop', flat ? { castShadow: false, ink: false, outline: false } : { ink: key !== 'leaf' });
            meshes.push(merged);
        }
        return { meshes };
    },

    _tree(add, scene, x, y, s) {
        const trunk = BABYLON.MeshBuilder.CreateCylinder('t', { height: 260 * s, diameterTop: 34 * s, diameterBottom: 46 * s, tessellation: 7 }, scene);
        trunk.position.set(x, 14 + 130 * s, y);
        add('trunk', trunk);
        const crown = BABYLON.MeshBuilder.CreateIcoSphere('c', { radius: 170 * s, subdivisions: 1 }, scene);
        crown.position.set(x, 14 + 380 * s, y);
        crown.scaling.y = 1.15;
        add('leaf', crown);
    },

    _lamp(add, scene, x, y) {
        const pole = BABYLON.MeshBuilder.CreateCylinder('p', { height: 520, diameter: 22, tessellation: 6 }, scene);
        pole.position.set(x, 14 + 260, y);
        add('lamp', pole);
        const head = BABYLON.MeshBuilder.CreateBox('h', { width: 90, height: 26, depth: 44 }, scene);
        head.position.set(x, 14 + 530, y);
        add('lampHead', head);
    },

    _car(add, scene, x, y, vertical, hex) {
        const L = 430, Wd = 190;
        const body = BABYLON.MeshBuilder.CreateBox('car', { width: vertical ? Wd : L, height: 80, depth: vertical ? L : Wd }, scene);
        body.position.set(x, 70, y);
        add('car' + hex, body);
        const cab = BABYLON.MeshBuilder.CreateBox('cab', { width: vertical ? Wd - 20 : L * 0.5, height: 70, depth: vertical ? L * 0.5 : Wd - 20 }, scene);
        cab.position.set(x, 145, y);
        add('glass', cab);
        for (const a of [-1, 1]) for (const b of [-1, 1]) {
            const w = BABYLON.MeshBuilder.CreateCylinder('w', { height: 30, diameter: 70, tessellation: 10 }, scene);
            w.rotation[vertical ? 'z' : 'x'] = Math.PI / 2;
            const ax = vertical ? a * (Wd / 2) : b * (L / 2 - 80), ay = vertical ? b * (L / 2 - 80) : a * (Wd / 2);
            w.position.set(x + ax, 35, y + ay);
            add('tyre', w);
        }
    },

    _plaza(add, box, scene, x0, y0, size, rnd) {
        // Lawns at the corners, a fountain in the middle, trees around the diagonal walk
        const q = size / 2;
        for (const [i, j] of [[0, 1], [1, 0]]) add('grass', box(q - 260, 8, q - 260, x0 + i * q + q / 2, 14, y0 + j * q + q / 2));
        const cx = x0 + q, cy = y0 + q;
        const ring = BABYLON.MeshBuilder.CreateCylinder('f', { height: 60, diameter: 620, tessellation: 28 }, scene);
        ring.position.set(cx + 380, 44, cy - 380);
        add('stone', ring);
        const water = BABYLON.MeshBuilder.CreateCylinder('fw', { height: 8, diameter: 560, tessellation: 28 }, scene);
        water.position.set(cx + 380, 72, cy - 380);
        add('water', water);
        const col = BABYLON.MeshBuilder.CreateCylinder('fc', { height: 200, diameterTop: 40, diameterBottom: 90, tessellation: 12 }, scene);
        col.position.set(cx + 380, 140, cy - 380);
        add('stone', col);
        for (let k = 0; k < 10; k++) {
            const a = rnd() * size, b = rnd() * size;
            if (Math.abs(a - b) < 520) continue;   // keep the diagonal walk clear
            this._tree(add, scene, x0 + a, y0 + b, 0.9 + rnd() * 0.5);
        }
        for (let k = 0; k < 4; k++) add('stone', box(260, 50, 70, x0 + 500 + k * 300, 14, y0 + size - 200));
    }
};

// Scene props: cones, barriers, crates — small meshes from the document objects.
/** @satisfies {Record<string, any>} */
const StudioProps = {
    build(view, o) {
        const scene = view.scene, root = new BABYLON.Mesh('prop/' + o.id, scene);
        const s = o.scale > 0 ? o.scale : 1;
        const part = (mesh, hex, x, y, z) => {
            mesh.material = StudioCity.mat(scene, 'pm/' + o.id + '/' + hex, hex);
            mesh.position.set(x, y, z);
            mesh.parent = root;
        };
        if (o.type === 'cone') {
            part(BABYLON.MeshBuilder.CreateCylinder('c', { height: 90, diameterTop: 10, diameterBottom: 62, tessellation: 14 }, scene), '#ff7a3d', 0, 59, 0);
            part(BABYLON.MeshBuilder.CreateCylinder('s', { height: 16, diameterTop: 30, diameterBottom: 38, tessellation: 14 }, scene), '#ffffff', 0, 70, 0);
            part(BABYLON.MeshBuilder.CreateBox('b', { width: 80, height: 10, depth: 80 }, scene), '#ff7a3d', 0, 19, 0);
        } else if (o.type === 'barrier') {
            for (const k of [-1, 1]) part(BABYLON.MeshBuilder.CreateBox('l', { width: 14, height: 110, depth: 60 }, scene), '#2b3a44', k * 150, 69, 0);
            part(BABYLON.MeshBuilder.CreateBox('r', { width: 340, height: 40, depth: 12 }, scene), '#ffffff', 0, 104, 0);
            for (let k = -2; k <= 2; k++) part(BABYLON.MeshBuilder.CreateBox('st', { width: 30, height: 41, depth: 13 }, scene), '#ff6b4a', k * 64, 104, 0);
        } else {
            part(BABYLON.MeshBuilder.CreateBox('cr', { width: 110, height: 110, depth: 110 }, scene), '#b98a5a', 0, 69, 0);
            part(BABYLON.MeshBuilder.CreateBox('cb', { width: 114, height: 16, depth: 114 }, scene), '#8a6440', 0, 69, 0);
        }
        root.scaling.setAll(s);
        World3D.addObject(view, root, 'prop');
        return root;
    }
};

// Actors: the generated GLB characters, posed from the baked frames. The run cycle is
// driven by DISTANCE (phase from StudioSim), not by time: feet do not slide at any speed,
// and scrubbing shows the exact pose.
/** @satisfies {Record<string, any>} */
const StudioActors = {
    _models: new Map(),

    load(scene, outfit) {
        const key = scene.uid + '|' + outfit;
        if (!this._models.has(key)) {
            const url = (typeof STUDIO_MODELS !== 'undefined' && STUDIO_MODELS[outfit]) || ('studio/assets/' + outfit + '.glb');
            const p = BABYLON.LoadAssetContainerAsync(url, scene, { pluginExtension: '.glb' }).then((container) => {
                for (const g of container.animationGroups) g.stop();
                scene.onDisposeObservable.addOnce(() => container.dispose());
                return { gltf: true, container, clips: container.animationGroups.map(g => g.name) };
            });
            this._models.set(key, p);
        }
        return this._models.get(key);
    },

    build(view, o) {
        const rec = { id: o.id, root: null, groups: null, ready: null };
        rec.ready = this.load(view.scene, o.outfit || 'chaser').then((model) => {
            const root = Gltf3D.build(model, view.scene, { name: 'actor/' + o.id });
            const clips = Gltf3D.clips(root);
            const groups = {};
            for (const [name, t] of clips.tracks) {
                t.group.start(true, 1, t.group.from, t.group.to, false);
                t.group.speedRatio = 0;          // frames are set by hand every frame
                groups[name] = t.group;
            }
            const s = o.scale > 0 ? o.scale : 1;
            root.scaling.setAll(s);
            World3D.addObject(view, root, 'actor');
            rec.root = root;
            rec.groups = groups;
            return rec;
        }).catch((e) => {
            console.warn('Студия: персонаж ' + o.id + ' не загрузился — ' + ((e && e.message) || e));
            return rec;
        });
        return rec;
    },

    // Pose an actor for its state: position, heading, lean, clip weights and frames.
    pose(rec, st, t) {
        if (!rec.root || !st) return;
        const r = rec.root;
        r.position.set(st.x, 14, st.y);
        r.rotationQuaternion = null;
        r.rotation.set(StudioActors.LEAN_SIGN * st.lean, -st.heading, 0);
        const v = st.speed;
        const run = Math.max(0, Math.min(1, v / 160));
        const sprint = Math.max(0, Math.min(1, (v - 720) / 140));
        const w = { idle: 1 - run, run: run * (1 - sprint), sprint: run * sprint };
        for (const name in rec.groups) {
            const g = rec.groups[name];
            const frac = name === 'idle' ? (t / 2.4) % 1 : (st.phase % 1 + 1) % 1;
            g.goToFrame(g.from + frac * (g.to - g.from));
            g.setWeightForAllAnimatables(Math.max(0.0001, w[name] || 0));
        }
    }
};
StudioActors.LEAN_SIGN = 1;

// The stage: city + props + actors + scene camera for one document.
class StudioStage {
    constructor(canvas) {
        this.canvas = canvas;
        this.view = World3D.createView({});
        this.terrain = new Terrain3D(this.view, { worldW: 10400, worldH: 10400, cell: 400, noise: { amp: 0, base: 0 } });
        this.terrain.material.diffuseColor = World3D.hexColor3(0x8a9aa6);
        this.terrain.outerMaterial.diffuseColor = World3D.hexColor3(0x8a9aa6);
        this.city = null;
        this.actors = new Map();
        this.props = new Map();
        this.cityKey = '';
    }

    // Rebuild what changed in the document: the city by its world record, props and actors by id.
    sync(doc) {
        const key = JSON.stringify(doc.world || {});
        if (key !== this.cityKey) {
            if (this.city) for (const m of this.city.meshes) World3D.removeObject(this.view, m);
            this.city = StudioCity.build(this.view, doc.world);
            this.cityKey = key;
        }
        const ids = new Set(doc.objects.map(o => o.id));
        for (const [id, rec] of this.actors) if (!ids.has(id) || rec.sig !== this._sig(doc, id)) { this._dropActor(id, rec); }
        for (const [id, m] of this.props) if (!ids.has(id) || m.sig !== this._sig(doc, id)) { World3D.removeObject(this.view, m.root); this.props.delete(id); }
        const waits = [];
        for (const o of doc.objects) {
            if (o.type === 'person') {
                if (!this.actors.has(o.id)) {
                    const rec = StudioActors.build(this.view, o);
                    rec.sig = this._sig(doc, o.id);
                    this.actors.set(o.id, rec);
                    waits.push(rec.ready);
                }
            } else if (!this.props.has(o.id)) {
                const root = StudioProps.build(this.view, o);
                const d = Math.PI / 180;
                root.position.set(o.x || 0, 0, o.y || 0);
                root.rotation.y = -(o.heading || 0) * d;
                this.props.set(o.id, { root, sig: this._sig(doc, o.id) });
            }
        }
        return Promise.all(waits);
    }

    _sig(doc, id) {
        const o = doc.objects.find(x => x.id === id);
        return o ? [o.type, o.outfit, o.scale, o.x, o.y, o.heading].join('|') : '';
    }

    _dropActor(id, rec) {
        if (rec.root) World3D.removeObject(this.view, rec.root);
        this.actors.delete(id);
    }

    // Show time t of the baked scene. camera: true — the scene camera drives the view.
    show(baked, t, camera) {
        for (const [id, rec] of this.actors) StudioActors.pose(rec, StudioSim.objectAt(baked, id, t), t);
        if (camera) {
            const c = StudioSim.cameraAt(baked, t);
            const cam = this.view.camera;
            cam.fov = c.fov * Math.PI / 180;
            cam.position.set(c.eye[0], Math.max(40, c.eye[2]), c.eye[1]);
            cam.setTarget(new BABYLON.Vector3(c.look[0], c.look[2], c.look[1]));
            this.lookAt = c.look;
            this.eyeAt = c.eye;
        }
    }

    // Shadows: a tight sun frustum around the action (the scene camera's look point).
    fitShadows(x, y, radius) {
        const R = Math.max(900, Math.min(2600, radius || 2000));
        const q = 2 * R / 2048;
        this.view.updateLightFrustum(Math.round(x / q) * q, Math.round(y / q) * q, 0, R);
    }
}
