// GENERATED by tools/build-studio.mjs from chase.json — the built-in "chase" scene.
const STUDIO_SCENE_CHASE = {
 "version": 1,
 "name": "Погоня",
 "duration": 18,
 "world": {
  "type": "city",
  "seed": 7,
  "plaza": [
   2,
   1
  ]
 },
 "objects": [
  {
   "id": "runner",
   "type": "person",
   "name": "Бегун",
   "outfit": "runner",
   "path": "route",
   "start": 0,
   "weave": 22
  },
  {
   "id": "chaser1",
   "type": "person",
   "name": "Преследователь 1",
   "outfit": "chaser"
  },
  {
   "id": "chaser2",
   "type": "person",
   "name": "Преследователь 2",
   "outfit": "chaser"
  },
  {
   "id": "chaser3",
   "type": "person",
   "name": "Преследователь 3",
   "outfit": "chaser"
  },
  {
   "id": "cone1",
   "type": "cone",
   "name": "Конус",
   "x": 3300,
   "y": 2930
  },
  {
   "id": "cone2",
   "type": "cone",
   "name": "Конус",
   "x": 3520,
   "y": 2945
  },
  {
   "id": "cone3",
   "type": "cone",
   "name": "Конус",
   "x": 3740,
   "y": 2955
  },
  {
   "id": "barrier1",
   "type": "barrier",
   "name": "Ограждение",
   "x": 7520,
   "y": 6200,
   "heading": 90
  },
  {
   "id": "crate1",
   "type": "crate",
   "name": "Ящик",
   "x": 6230,
   "y": 8080
  },
  {
   "id": "crate2",
   "type": "crate",
   "name": "Ящик",
   "x": 6330,
   "y": 8120,
   "scale": 0.8
  }
 ],
 "paths": [
  {
   "id": "route",
   "points": [
    [
     900,
     2600
    ],
    [
     2600,
     2560
    ],
    [
     4300,
     2620
    ],
    [
     4950,
     2680
    ],
    [
     5350,
     2980
    ],
    [
     6400,
     3880
    ],
    [
     7350,
     4750
    ],
    [
     7760,
     5300
    ],
    [
     7820,
     6500
    ],
    [
     7760,
     7450
    ],
    [
     7400,
     7790
    ],
    [
     6500,
     7840
    ],
    [
     5400,
     7800
    ]
   ]
  }
 ],
 "keyframes": [
  {
   "target": "runner",
   "prop": "speed",
   "t": 0,
   "value": 0
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 0.5,
   "value": 0
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 1.4,
   "value": 620
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 4,
   "value": 700
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 7,
   "value": 670
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 9.5,
   "value": 720
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 12,
   "value": 690
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 14.5,
   "value": 830
  },
  {
   "target": "runner",
   "prop": "speed",
   "t": 18,
   "value": 860
  },
  {
   "target": "chase3",
   "prop": "aggression",
   "t": 10,
   "value": 0.6
  },
  {
   "target": "chase3",
   "prop": "aggression",
   "t": 13,
   "value": 1
  },
  {
   "target": "chase1",
   "prop": "lane",
   "t": 6,
   "value": 150
  },
  {
   "target": "chase1",
   "prop": "lane",
   "t": 9,
   "value": -60
  }
 ],
 "behaviors": [
  {
   "id": "chase1",
   "type": "chase",
   "hunter": "chaser1",
   "prey": "runner",
   "aggression": 0.7,
   "gap": 1100,
   "minGap": 300,
   "maxSpeed": 800,
   "accel": 900,
   "lane": 150,
   "delay": 1
  },
  {
   "id": "chase2",
   "type": "chase",
   "hunter": "chaser2",
   "prey": "runner",
   "aggression": 0.55,
   "gap": 1500,
   "minGap": 420,
   "maxSpeed": 780,
   "accel": 850,
   "lane": -160,
   "delay": 1.4
  },
  {
   "id": "chase3",
   "type": "chase",
   "hunter": "chaser3",
   "prey": "runner",
   "aggression": 0.6,
   "gap": 2000,
   "minGap": 260,
   "maxSpeed": 860,
   "accel": 1000,
   "lane": 20,
   "delay": 1.9
  }
 ],
 "camera": {
  "blend": 0.8,
  "shots": [
   {
    "t": 0,
    "mode": "flyby",
    "target": "runner",
    "lookHeight": 110,
    "fov": 48,
    "keys": [
     {
      "t": 0,
      "eye": [
       -1100,
       2650,
       2300
      ]
     },
     {
      "t": 1.9,
      "eye": [
       -150,
       2420,
       900
      ]
     },
     {
      "t": 3.6,
      "eye": [
       620,
       2860,
       250
      ]
     }
    ]
   },
   {
    "t": 3.6,
    "mode": "follow",
    "target": "runner",
    "angle": 180,
    "distance": 760,
    "height": 230,
    "lookAhead": -520,
    "lookHeight": 120,
    "smooth": 0.4,
    "fov": 50
   },
   {
    "t": 7.2,
    "mode": "static",
    "eye": [
     5900,
     2380,
     170
    ],
    "target": "runner",
    "smooth": 0.25,
    "fov": 46
   },
   {
    "t": 9.6,
    "mode": "follow",
    "target": "runner",
    "angle": -25,
    "distance": 520,
    "height": 1500,
    "lookAhead": 200,
    "lookHeight": 0,
    "smooth": 0.5,
    "fov": 50
   },
   {
    "t": 12.4,
    "mode": "follow",
    "target": "runner",
    "angle": 90,
    "distance": 680,
    "height": 170,
    "lookAhead": -250,
    "lookHeight": 110,
    "smooth": 0.35,
    "fov": 50
   },
   {
    "t": 16,
    "mode": "static",
    "eye": [
     4650,
     7740,
     150
    ],
    "target": "runner",
    "smooth": 0.3,
    "fov": 40
   }
  ]
 }
};
